service: home-dashboard-backend
frameworkVersion: '3'
useDotenv: true

provider:
  lambdaHashingVersion: 20201221
  name: aws
  region: eu-west-1
  runtime: nodejs24.x
  stage: api
  timeout: 30

package:
  patterns:
    - '!**'
    - dist/**
    - node_modules/**

functions:
  - ${file(./src/lambdas/config/infra/function.yml)}
  - ${file(./src/lambdas/google-calendar/infra/function.yml)}
  - ${file(./src/lambdas/news/infra/function.yml)}

resources:
  - ${file(./src/lambdas/config/infra/resources.yml)}
  - ${file(./src/lambdas/google-calendar/infra/resources.yml)}
  - ${file(./src/lambdas/news/infra/resources.yml)}
  - ${file(./infra/s3.yml)}