service: home-dashboard-backend
frameworkVersion: '3'
useDotenv: true
provider:
  lambdaHashingVersion: 20201221
  name: aws
  region: eu-west-1
  runtime: nodejs24.x
  stage: api
  timeout: 30
  iam:
    role:
      statements:
      - Effect: "Allow"
        Action:
        - "s3:ListAllMyBuckets"
        - "s3:GetBucketLocation"
        Resource: "*"
package:
  patterns:
  - '!**' # exclude everything by default, then include stuff below
  - 'dist/**'
  - 'node_modules/**'
functions:
  config:
    name: home-dashboard-config
    description: CRUD operations for config for Home Dashboard
    handler: dist/src/api/config.handler
    logRetentionInDays: 7
    events:
    - http:
        method: get
        path: /config
        cors: true
    - http:
        method: post
        path: /config
        cors: true
