service: home-dashboard-backend
frameworkVersion: '3'
useDotenv: true

provider:
  lambdaHashingVersion: 20201221
  name: aws
  region: eu-west-1
  runtime: nodejs24.x
  stage: api
  timeout: 30

package:
  patterns:
    - '!**'
    - dist/**
    - node_modules/**

functions:
  config: ${file(./src/lambdas/config/infra.yml):function}
  news: ${file(./src/lambdas/news/infra.yml):function}
  calendar: ${file(./src/lambdas/google-calendar/infra.yml):function}

resources:
  Resources:
    ConfigLambdaRole: ${file(./src/lambdas/config/infra.yml):role}
    NewsLambdaRole: ${file(./src/lambdas/news/infra.yml):role}
    CalendarLambdaRole: ${file(./src/lambdas/google-calendar/infra.yml):role}
    ConfigBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: home-dashboard-config
        PublicAccessBlockConfiguration:
          BlockPublicAcls: true
          IgnorePublicAcls: true
          BlockPublicPolicy: true
          RestrictPublicBuckets: true