---
todoist:
  description: Lambda that backs onto the Todoist API
  events:
    - http:
        cors: true
        method: get
        path: /todoist
    - http:
        cors: true
        method: post
        path: /todoist
    - http:
        cors: true
        method: delete
        path: /todoist
  handler: dist/src/lambdas/todoist/handler.handler
  logRetentionInDays: 7
  name: home-dashboard-todoist
  role:
    Fn::GetAtt:
      - TodoistLambdaRole
      - Arn